#!/bin/bash
clear
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
WKT=$(curl -s ipinfo.io/timezone )
IPVPS=$(curl -s ifconfig.me/ip )
echo -e ""                
echo -e "				╔══╗╔═══╦═══╦═══╦═╗╔═╦╗──╔╦════╗"
echo -e "				║╔╗║║╔═╗╠╗╔╗║╔═╗╠╗╚╝╔╣╚╗╔╝╠══╗═║"
echo -e "				║╚╝╚╣║─║║║║║║║─║║╚╗╔╝╚╗╚╝╔╝─╔╝╔╝"
echo -e "				║╔═╗║╚═╝║║║║║║─║║╔╝╚╗─╚╗╔╝─╔╝╔╝"
echo -e "				║╚═╝║╔═╗╠╝╚╝║╚═╝╠╝╔╗╚╗─║║─╔╝═╚═╗"
echo -e "				╚═══╩╝─╚╩═══╩═══╩═╝╚═╝─╚╝─╚════╝"
echo -e ""
echo -e "----------------------------------------------------------------"
echo -e "- IP Vps        : $IPVPS"
echo -e "- Isp Vps Name  : $ISP"
echo -e "- Region        : $CITY"
echo -e "- Time          : $WKT"
echo -e "----------------------------------------------------------------"
echo -e ""
echo -e "=============================-Menu-============================="
echo -e "# menu         : List of Main Commands"
echo -e "================================================================"
echo -e ""
echo -e "=======================-SSH & OpenVPN WS-======================="
echo -e "# usernew      : Create Account"
echo -e "# trial        : Generate Trial Account"
echo -e "# renew        : Extending Account Active Life"
echo -e "# deluser      : Delete Account"
echo -e "# cek          : Check User Login"
echo -e "# member       : Daftar Member"
echo -e "# delete       : Delete Expired Account"
echo -e "# autokill     : Set up Autokill Account"
echo -e "# ceklim       : Displays Users Who Do Multi Login"
echo -e "# restart      : Restart Service"
echo -e "================================================================"
echo -e ""
echo -e "===========================-Wireguard-=========================="
echo -e "# add-wg       : Create Account"
echo -e "# del-wg       : Delete Account"
echo -e "# cek-wg       : Check User Login"
echo -e "# renew-wg     : Extending Wireguard Account Active Life"
echo -e "# wg show      : Check Wireguard User Interface"
echo -e "================================================================"
echo -e ""
echo -e "=============================-L2TP-============================="
echo -e "# add-l2tp     : Creating Account"
echo -e "# del-l2tp     : Deleting Account"
echo -e "# renew-l2tp   : Extending L2TP Account Active Life"
echo -e "================================================================"
echo -e ""
echo -e "=============================-PPTP-============================="
echo -e "# add-pptp     : Create Account"
echo -e "# del-pptp     : Delete Account"
echo -e "# renew-pptp   : Extending PPTP Account Active Life"
echo -e "# cek-pptp     : Check User Login"
echo -e "================================================================"
echo -e ""
echo -e "=============================-SSTP-============================="
echo -e "# add-sstp     : Create Account"
echo -e "# del-sstp     : Delete Account"
echo -e "# renew-sstp   : Extending Account Active Life"
echo -e "# cek-sstp     : Check User Login"
echo -e "================================================================"
echo -e ""
echo -e "=============================-SSR-=============================="
echo -e "# add-ssr      : Create Account"
echo -e "# del-ssr      : Deleting Account"
echo -e "# renew-ssr    : Extending Account Active Life"
echo -e "# ssr          : Show Other Menu"
echo -e "================================================================"
echo -e ""
echo -e "========================-Shadowsocks OBFS-======================"
echo -e "# add-ss       : Create Account"
echo -e "# del-ss       : Delete Account"
echo -e "# renew-ss     : Extending Account Active Life"
echo -e "# cek-ss       : Check User Login"
echo -e "================================================================"
echo -e ""
echo -e "=============================-VMESS-============================"
echo -e "# add-ws       : Create Account"
echo -e "# del-ws       : Deleting Account"
echo -e "# renew-ws     : Extending Account Active Life"
echo -e "# cek-ws       : Check User Login"
echo -e "# cert2vray    : Renew Certificate V2RAY Account"
echo -e "================================================================"
echo -e ""
echo -e "=============================-VLESS-============================"
echo -e "# add-vless    : Create Account"
echo -e "# del-vless    : Deleting Account"
echo -e "# renew-vless  : Extending Account Active Life"
echo -e "# cek-ws       : Check User Login"
echo -e "================================================================"
echo -e ""
echo -e "=============================-Trojan-==========================="
echo -e "# add-tr       : Create Account"
echo -e "# del-tr       : Deleting Account"
echo -e "# renew-tr     : Extending Account Active Life"
echo -e "# cek-tr       : Check User Login"
echo -e "================================================================"
echo -e ""
echo -e "=============================-SYSTEM-==========================="
echo -e "# add-host     : Add Or Change Domain"
echo -e "# change-port  : Change Port Service"
echo -e "# autobackup   : Autobackup Data VPS"
echo -e "# backup       : Backup Data VPS"
echo -e "# restore      : Restore Data VPS"
echo -e "# wbmn         : Webmin Menu"
echo -e "# kernel-updt  : Update To Latest Kernel"
echo -e "# limit-speed  : Limit Bandwith Speed Server"
echo -e "# ram          : Check Usage of VPS Ram"
echo -e "# reboot       : Reboot VPS"
echo -e "# speedtest    : Speedtest VPS"
echo -e "# update       : Update To Latest Script Version"
echo -e "# info         : Displaying System Information"
echo -e "# about        : Info Script Auto Install"
echo -e "# exit         : Exit From VPS"
echo -e "==============================================================="
echo -e "Script Installed By Badoxyz"
echo -e ""